#!/bin/bash
for i in $(lid -ng zarco-data)
do
	username=$i
	echo $username
	homedir=$(getent passwd $username | cut -d: -f6)
	if [[ ! -z "$homedir" ]] && [ -d "$homedir" ]; then
		echo "adding jupyterhub-tree to $homedir"
		mkdir $homedir/$username/.jupyterhub-tree/
		ln -fsT $homedir/$username/ $homedir/.jupyterhub-tree/home
		mkdir  $homedir/work/
		chown $username:$username $homedir/work/
		ln -fsT $homedir/$username/work/ $homedir/.jupyterhub-tree/work
		mkdir /scratch/$username/
		chown $username:$username /scratch/$username/
		ln -fsT /scratch/$username/ $homedir/.jupyterhub-tree/scratch
		chown -R $username:$username $homedir/.jupyterhub-tree/
	fi

done
